/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c1d5295e-0033-4c65-8e55-ad253308ca77",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3Avp9IRFD",
    "aws_user_pools_web_client_id": "7r07di9jvvk1qskqnsi41u0mbt",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4zgpi2lzgbgdvgiv6oi6kgjcae.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mrejqmn2yjge5l56rog3zi43n4",
    "aws_user_files_s3_bucket": "amplify-bucket-torakozic180357-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
